[profile.default]
src = 'src'
out = 'artifacts/foundry'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache/foundry'
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
